apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: web-server
    name: web-server
    namespace: default
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30719
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      run: web-server
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    generation: 1
    labels:
      run: web-server
    name: web-server
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        run: web-server
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: web-server
      spec:
        containers:
        - image: YOUR_IMAGE_LOCATION
          imagePullPolicy: Always
          name: web-server
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
kind: List
metadata:
  resourceVersion: ""
